//! C++ code generator for .bridge IDL schemas.
//! Generates packed structs with static_assert for layout verification.

use crate::ast::*;
use crate::layout::*;
use std::fmt::Write;

pub fn generate(schema: &Schema, layout: &SchemaLayout) -> String {
    let mut out = String::new();

    writeln!(out, "// Auto-generated by synapse-idl. Do not edit.").unwrap();
    writeln!(out, "#pragma once").unwrap();
    writeln!(out, "#include <cstdint>").unwrap();
    writeln!(out, "#include <cstring>").unwrap();
    writeln!(out).unwrap();

    if let Some(ns) = &schema.namespace {
        writeln!(out, "namespace {} {{", ns).unwrap();
        writeln!(out).unwrap();
    }

    for item in &schema.items {
        match item {
            Item::Struct(def) => {
                let sl = &layout.structs[&def.name];
                gen_struct(&mut out, def, sl);
            }
            Item::Enum(def) => {
                let el = &layout.enums[&def.name];
                gen_enum(&mut out, def, el);
            }
            Item::Channel(def) => {
                gen_channel_comment(&mut out, def);
            }
        }
    }

    if schema.namespace.is_some() {
        writeln!(out, "}} // namespace").unwrap();
    }

    out
}

fn gen_struct(out: &mut String, def: &StructDef, sl: &StructLayout) {
    writeln!(out, "struct {} {{", def.name).unwrap();
    for field in &def.fields {
        write_cpp_field(out, &field.name, &field.ty, "    ");
    }
    writeln!(out, "}};").unwrap();
    writeln!(
        out,
        "static_assert(sizeof({}) == {}, \"layout mismatch\");",
        def.name, sl.size
    )
    .unwrap();
    writeln!(
        out,
        "static_assert(alignof({}) == {}, \"alignment mismatch\");",
        def.name, sl.align
    )
    .unwrap();
    writeln!(out).unwrap();
}

fn gen_enum(out: &mut String, def: &EnumDef, el: &EnumLayout) {
    // Tag enum
    writeln!(out, "enum class {}Tag : uint32_t {{", def.name).unwrap();
    for (i, variant) in def.variants.iter().enumerate() {
        writeln!(out, "    {} = {},", variant.name, i).unwrap();
    }
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();

    // Payload structs
    for variant in &def.variants {
        if !variant.fields.is_empty() {
            writeln!(out, "struct {}{}Payload {{", def.name, variant.name).unwrap();
            for field in &variant.fields {
                write_cpp_field(out, &field.name, &field.ty, "    ");
            }
            writeln!(out, "}};").unwrap();
            writeln!(out).unwrap();
        }
    }

    // Tagged union struct
    writeln!(out, "struct {} {{", def.name).unwrap();
    writeln!(out, "    {}Tag tag;", def.name).unwrap();
    writeln!(out, "    uint8_t payload[{}];", el.max_payload_size).unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(
        out,
        "static_assert(sizeof({}) == {}, \"layout mismatch\");",
        def.name, el.size
    )
    .unwrap();
    writeln!(out).unwrap();
}

fn gen_channel_comment(out: &mut String, def: &ChannelDef) {
    writeln!(out, "// Channel: {}", def.name).unwrap();
    for entry in &def.entries {
        writeln!(out, "//   {}: {}", entry.name, entry.ty).unwrap();
    }
    writeln!(out).unwrap();
}

/// Write a C++ field declaration, handling array syntax correctly.
/// In C++, arrays are `type name[size]`, not `type[size] name`.
fn write_cpp_field(out: &mut String, name: &str, ty: &Type, indent: &str) {
    match ty {
        Type::Array(inner, count) => {
            writeln!(out, "{}{} {}[{}];", indent, cpp_type(inner), name, count).unwrap();
        }
        _ => {
            writeln!(out, "{}{} {};", indent, cpp_type(ty), name).unwrap();
        }
    }
}

fn cpp_type(ty: &Type) -> String {
    match ty {
        Type::Primitive(p) => primitive_cpp(p).to_string(),
        Type::Array(inner, count) => format!("{}[{}]", cpp_type(inner), count),
        Type::Named(name) => name.clone(),
    }
}

fn primitive_cpp(p: &PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::U8 => "uint8_t",
        PrimitiveType::U16 => "uint16_t",
        PrimitiveType::U32 => "uint32_t",
        PrimitiveType::U64 => "uint64_t",
        PrimitiveType::I8 => "int8_t",
        PrimitiveType::I16 => "int16_t",
        PrimitiveType::I32 => "int32_t",
        PrimitiveType::I64 => "int64_t",
        PrimitiveType::F32 => "float",
        PrimitiveType::F64 => "double",
        PrimitiveType::Bool => "bool",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layout::compute_layout;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn gen(input: &str) -> String {
        let mut lexer = Lexer::new(input);
        let tokens = lexer.tokenize().unwrap();
        let mut parser = Parser::new(tokens);
        let schema = parser.parse().unwrap();
        let layout = compute_layout(&schema).unwrap();
        generate(&schema, &layout)
    }

    #[test]
    fn test_struct_gen() {
        let code = gen("struct Vec3f { x: f32, y: f32, z: f32, }");
        assert!(code.contains("struct Vec3f {"));
        assert!(code.contains("float x;"));
        assert!(code.contains("static_assert(sizeof(Vec3f) == 12"));
        assert!(code.contains("static_assert(alignof(Vec3f) == 4"));
    }

    #[test]
    fn test_enum_gen() {
        let code = gen("enum Cmd { Move { x: u32 }, Idle, }");
        assert!(code.contains("enum class CmdTag : uint32_t"));
        assert!(code.contains("Move = 0"));
        assert!(code.contains("Idle = 1"));
        assert!(code.contains("struct CmdMovePayload"));
        assert!(code.contains("CmdTag tag;"));
    }

    #[test]
    fn test_array_field() {
        let code = gen("struct Buf { data: [u8; 32], }");
        assert!(code.contains("uint8_t data[32]"));
    }

    #[test]
    fn test_namespace() {
        let code = gen("namespace game;\nstruct A { x: u8, }");
        assert!(code.contains("namespace game {"));
        assert!(code.contains("} // namespace"));
    }

    #[test]
    fn test_pragma_once() {
        let code = gen("struct A { x: u8, }");
        assert!(code.contains("#pragma once"));
        assert!(code.contains("#include <cstdint>"));
    }
}
