//! Python ctypes code generator for .bridge IDL schemas.

use crate::ast::*;
use crate::layout::*;
use std::fmt::Write;

pub fn generate(schema: &Schema, layout: &SchemaLayout) -> String {
    let mut out = String::new();

    writeln!(out, "# Auto-generated by synapse-idl. Do not edit.").unwrap();
    writeln!(out, "import ctypes").unwrap();
    writeln!(out).unwrap();

    if let Some(ns) = &schema.namespace {
        writeln!(out, "# Namespace: {ns}").unwrap();
        writeln!(out).unwrap();
    }

    for item in &schema.items {
        match item {
            Item::Struct(def) => {
                let sl = &layout.structs[&def.name];
                gen_struct(&mut out, def, sl);
            }
            Item::Enum(def) => {
                let el = &layout.enums[&def.name];
                gen_enum(&mut out, def, el);
            }
            Item::Channel(def) => {
                gen_channel_comment(&mut out, def);
            }
        }
    }

    out
}

fn gen_struct(out: &mut String, def: &StructDef, sl: &StructLayout) {
    writeln!(
        out,
        "class {}(ctypes.Structure):  # size={}, align={}",
        def.name, sl.size, sl.align
    )
    .unwrap();
    writeln!(out, "    _pack_ = {}", sl.align).unwrap();
    writeln!(out, "    _fields_ = [").unwrap();
    for field in &def.fields {
        writeln!(
            out,
            "        (\"{}\", {}),",
            field.name,
            python_ctype(&field.ty)
        )
        .unwrap();
    }
    writeln!(out, "    ]").unwrap();
    writeln!(out).unwrap();
}

fn gen_enum(out: &mut String, def: &EnumDef, el: &EnumLayout) {
    // Tag constants
    for (i, variant) in def.variants.iter().enumerate() {
        writeln!(
            out,
            "{}_{} = {}",
            to_screaming(&def.name),
            to_screaming(&variant.name),
            i
        )
        .unwrap();
    }
    writeln!(out).unwrap();

    // Payload structs for variants with fields
    for variant in &def.variants {
        if !variant.fields.is_empty() {
            writeln!(
                out,
                "class {}{}Payload(ctypes.Structure):",
                def.name, variant.name
            )
            .unwrap();
            writeln!(out, "    _fields_ = [").unwrap();
            for field in &variant.fields {
                writeln!(
                    out,
                    "        (\"{}\", {}),",
                    field.name,
                    python_ctype(&field.ty)
                )
                .unwrap();
            }
            writeln!(out, "    ]").unwrap();
            writeln!(out).unwrap();
        }
    }

    // Tagged union
    writeln!(
        out,
        "class {}(ctypes.Structure):  # size={}, align={}",
        def.name, el.size, el.align
    )
    .unwrap();
    writeln!(out, "    _pack_ = {}", el.align).unwrap();
    writeln!(out, "    _fields_ = [").unwrap();
    writeln!(out, "        (\"tag\", ctypes.c_uint32),").unwrap();
    writeln!(
        out,
        "        (\"payload\", ctypes.c_uint8 * {}),",
        el.max_payload_size
    )
    .unwrap();
    writeln!(out, "    ]").unwrap();
    writeln!(out).unwrap();
}

fn gen_channel_comment(out: &mut String, def: &ChannelDef) {
    writeln!(out, "# Channel: {}", def.name).unwrap();
    for entry in &def.entries {
        writeln!(out, "#   {}: {}", entry.name, entry.ty).unwrap();
    }
    writeln!(out).unwrap();
}

fn python_ctype(ty: &Type) -> String {
    match ty {
        Type::Primitive(p) => primitive_ctype(p).to_string(),
        Type::Array(inner, count) => format!("{} * {}", python_ctype(inner), count),
        Type::Named(name) => name.clone(),
    }
}

fn primitive_ctype(p: &PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::U8 => "ctypes.c_uint8",
        PrimitiveType::U16 => "ctypes.c_uint16",
        PrimitiveType::U32 => "ctypes.c_uint32",
        PrimitiveType::U64 => "ctypes.c_uint64",
        PrimitiveType::I8 => "ctypes.c_int8",
        PrimitiveType::I16 => "ctypes.c_int16",
        PrimitiveType::I32 => "ctypes.c_int32",
        PrimitiveType::I64 => "ctypes.c_int64",
        PrimitiveType::F32 => "ctypes.c_float",
        PrimitiveType::F64 => "ctypes.c_double",
        PrimitiveType::Bool => "ctypes.c_bool",
    }
}

fn to_screaming(name: &str) -> String {
    let mut result = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_uppercase().next().unwrap());
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layout::compute_layout;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn gen(input: &str) -> String {
        let mut lexer = Lexer::new(input);
        let tokens = lexer.tokenize().unwrap();
        let mut parser = Parser::new(tokens);
        let schema = parser.parse().unwrap();
        let layout = compute_layout(&schema).unwrap();
        generate(&schema, &layout)
    }

    #[test]
    fn test_struct_gen() {
        let code = gen("struct Vec3f { x: f32, y: f32, z: f32, }");
        assert!(code.contains("class Vec3f(ctypes.Structure)"));
        assert!(code.contains("(\"x\", ctypes.c_float)"));
        assert!(code.contains("_pack_ = 4"));
    }

    #[test]
    fn test_enum_gen() {
        let code = gen("enum Cmd { Move { x: u32 }, Idle, }");
        assert!(code.contains("CMD_MOVE = 0"));
        assert!(code.contains("CMD_IDLE = 1"));
        assert!(code.contains("class CmdMovePayload(ctypes.Structure)"));
        assert!(code.contains("class Cmd(ctypes.Structure)"));
        assert!(code.contains("(\"tag\", ctypes.c_uint32)"));
    }

    #[test]
    fn test_array_field() {
        let code = gen("struct Buf { data: [u8; 32], }");
        assert!(code.contains("(\"data\", ctypes.c_uint8 * 32)"));
    }

    #[test]
    fn test_import() {
        let code = gen("struct A { x: u8, }");
        assert!(code.contains("import ctypes"));
    }
}
