//! Rust code generator for .bridge IDL schemas.
//! Generates `#[repr(C)]` structs and tagged union enums.

use crate::ast::*;
use crate::layout::*;
use std::fmt::Write;

pub fn generate(schema: &Schema, layout: &SchemaLayout) -> String {
    let mut out = String::new();

    writeln!(out, "// Auto-generated by synapse-idl. Do not edit.").unwrap();
    writeln!(out).unwrap();

    if let Some(ns) = &schema.namespace {
        writeln!(out, "/// Namespace: {ns}").unwrap();
        writeln!(out).unwrap();
    }

    for item in &schema.items {
        match item {
            Item::Struct(def) => {
                let sl = &layout.structs[&def.name];
                gen_struct(&mut out, def, sl);
            }
            Item::Enum(def) => {
                let el = &layout.enums[&def.name];
                gen_enum(&mut out, def, el);
            }
            Item::Channel(def) => {
                gen_channel_comment(&mut out, def);
            }
        }
    }

    out
}

fn gen_struct(out: &mut String, def: &StructDef, sl: &StructLayout) {
    writeln!(
        out,
        "/// Size: {} bytes, Align: {} bytes",
        sl.size, sl.align
    )
    .unwrap();
    writeln!(out, "#[repr(C)]").unwrap();
    writeln!(out, "#[derive(Debug, Clone, Copy)]").unwrap();
    writeln!(out, "pub struct {} {{", def.name).unwrap();
    for field in &def.fields {
        writeln!(out, "    pub {}: {},", field.name, rust_type(&field.ty)).unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn gen_enum(out: &mut String, def: &EnumDef, el: &EnumLayout) {
    // Generate variant tag constants
    writeln!(
        out,
        "/// Size: {} bytes, Align: {} bytes",
        el.size, el.align
    )
    .unwrap();
    writeln!(out, "pub mod {}_variants {{", to_snake(&def.name)).unwrap();
    for (i, variant) in def.variants.iter().enumerate() {
        writeln!(
            out,
            "    pub const {}: u32 = {};",
            to_screaming(&variant.name),
            i
        )
        .unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Generate payload structs for variants with fields
    for variant in &def.variants {
        if !variant.fields.is_empty() {
            writeln!(out, "#[repr(C)]").unwrap();
            writeln!(out, "#[derive(Debug, Clone, Copy)]").unwrap();
            writeln!(out, "pub struct {}{}Payload {{", def.name, variant.name).unwrap();
            for field in &variant.fields {
                writeln!(out, "    pub {}: {},", field.name, rust_type(&field.ty)).unwrap();
            }
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
    }

    // Generate the tagged union struct
    writeln!(out, "#[repr(C)]").unwrap();
    writeln!(out, "#[derive(Clone, Copy)]").unwrap();
    writeln!(out, "pub struct {} {{", def.name).unwrap();
    writeln!(out, "    pub tag: u32,").unwrap();
    writeln!(
        out,
        "    pub payload: [u8; {}],",
        el.max_payload_size
            .max(payload_offset(el) + el.max_payload_size - payload_offset(el))
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn payload_offset(el: &EnumLayout) -> usize {
    align_up(el.tag_size, el.max_payload_align)
}

fn align_up(offset: usize, align: usize) -> usize {
    if align == 0 {
        return offset;
    }
    (offset + align - 1) & !(align - 1)
}

fn gen_channel_comment(out: &mut String, def: &ChannelDef) {
    writeln!(out, "/// Channel: {}", def.name).unwrap();
    for entry in &def.entries {
        writeln!(out, "///   {}: {}", entry.name, entry.ty).unwrap();
    }
    writeln!(out).unwrap();
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::Primitive(p) => primitive_rust(p).to_string(),
        Type::Array(inner, count) => format!("[{}; {}]", rust_type(inner), count),
        Type::Named(name) => name.clone(),
    }
}

fn primitive_rust(p: &PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::U8 => "u8",
        PrimitiveType::U16 => "u16",
        PrimitiveType::U32 => "u32",
        PrimitiveType::U64 => "u64",
        PrimitiveType::I8 => "i8",
        PrimitiveType::I16 => "i16",
        PrimitiveType::I32 => "i32",
        PrimitiveType::I64 => "i64",
        PrimitiveType::F32 => "f32",
        PrimitiveType::F64 => "f64",
        PrimitiveType::Bool => "bool",
    }
}

fn to_snake(name: &str) -> String {
    let mut result = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_lowercase().next().unwrap());
    }
    result
}

fn to_screaming(name: &str) -> String {
    to_snake(name).to_uppercase()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layout::compute_layout;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn gen(input: &str) -> String {
        let mut lexer = Lexer::new(input);
        let tokens = lexer.tokenize().unwrap();
        let mut parser = Parser::new(tokens);
        let schema = parser.parse().unwrap();
        let layout = compute_layout(&schema).unwrap();
        generate(&schema, &layout)
    }

    #[test]
    fn test_struct_gen() {
        let code = gen("struct Vec3f { x: f32, y: f32, z: f32, }");
        assert!(code.contains("#[repr(C)]"));
        assert!(code.contains("pub struct Vec3f"));
        assert!(code.contains("pub x: f32"));
        assert!(code.contains("Size: 12 bytes"));
    }

    #[test]
    fn test_enum_gen() {
        let code = gen("enum Cmd { Move { x: u32 }, Idle, }");
        assert!(code.contains("pub const MOVE: u32 = 0"));
        assert!(code.contains("pub const IDLE: u32 = 1"));
        assert!(code.contains("pub struct CmdMovePayload"));
        assert!(code.contains("pub struct Cmd"));
        assert!(code.contains("pub tag: u32"));
    }

    #[test]
    fn test_array_field() {
        let code = gen("struct Buf { data: [u8; 32], }");
        assert!(code.contains("pub data: [u8; 32]"));
    }

    #[test]
    fn test_channel_comment() {
        let code = gen("channel ch { a: Foo, b: Bar, }");
        assert!(code.contains("Channel: ch"));
        assert!(code.contains("a: Foo"));
        assert!(code.contains("b: Bar"));
    }

    #[test]
    fn test_namespace_comment() {
        let code = gen("namespace game;\nstruct A { x: u8, }");
        assert!(code.contains("Namespace: game"));
    }
}
